vb/urls.py
from django.conf.urls import url
from django.contrib import admin
from cover import views as cover_views
from profiles import views as profiles_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', cover_views.get_index, name='index'),
    url(r'^register/$', profiles_views.register, name='register'),
    url(r'^login/$', profiles_views.login, name='login'),
    url(r'^logout/$', profiles_views.logout, name='logout'),
    url(r'^profile/$', profiles_views.profile, name='profile'),
    url(r'^newemployee/$', profiles_views.new_employee, name='newemployee'),
    url(r'^newinvoice/$', profiles_views.new_invoice, name='newinvoice'),
    url(r'^newcredit/$', profiles_views.new_credit, name='newcredit'),
    url(r'^newanalytics/$', profiles_views.new_analytics, name='newanalytics'),
    url(r'^credits/$', profiles_views.show_credit, name='credits'),
    url(r'^deletecredits/$', profiles_views.credit_delete, name='deletecredit'),
    url(r'^employees/$', profiles_views.show_employee, name='employees'),
    url(r'^employees/delete$', profiles_views.employee_delete, name='deleteemployee'),
    url(r'^invoices/$', profiles_views.show_invoice, name='invoices'),
    url(r'^invoices/delete$', profiles_views.invoice_delete, name='deleteinvoice'),
    url(r'^analytics/$', profiles_views.show_analytics, name='analytics'),
    url(r'^employees/api/data/$', profiles_views.EmpView.as_view()),
    url(r'^credits/api/data/$', profiles_views.CreditView.as_view()),
    url(r'^invoices/api/data/$', profiles_views.InvoiceView.as_view()),
    url(r'^analytics/api/data/$', profiles_views.AnalyticsView.as_view()),
]

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from profiles.models import User
from django.core.exceptions import ValidationError 
from .models import Employee, Invoice, Credit, Analytics
 
class UserRegistrationForm(UserCreationForm):
    MONTH_ABBREVIATIONS = [
        'Jan', 'Feb', 'Mar', 'Apr', 'May', 'June',
        'July', 'Aug', 'Sept', 'Oct', 'Nov', 'Dec'
    ]
    MONTH_CHOICES = list(enumerate(MONTH_ABBREVIATIONS, 1))
    YEAR_CHOICES = [(i, i) for i in range(2015, 2036)]
 
    credit_card_number = forms.CharField(label='Credit card number')
    cvv = forms.CharField(label='Security code (CVV)')
    expiry_month = forms.ChoiceField(label="Month", choices=MONTH_CHOICES)
    expiry_year = forms.ChoiceField(label="Year", choices=YEAR_CHOICES)
    stripe_id = forms.CharField(widget=forms.HiddenInput)
    password1 = forms.CharField(
        label='Password',
        widget=forms.PasswordInput
    )
 
    password2 = forms.CharField(
        label='Password Confirmation',
        widget=forms.PasswordInput
    )
 
    class Meta:
        model = User
        fields = ['email', 'password1', 'password2']
        exclude = ['username']
 
    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
 
        if password1 and password2 and password1 != password2:
            message = "Passwords do not match"
            raise ValidationError(message)
 
        return password2
 
    def save(self, commit=True):
        instance = super(UserRegistrationForm, self).save(commit=False)
 
        # automatically set to email address to create a unique identifier
        instance.username = instance.email
 
        if commit:
            instance.save()
 
        return instance

class UserLoginForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)


class EmployeeForm(forms.ModelForm):
 
    class Meta:
        model = Employee
        exclude = ['user']
        fields = ('name', 'contact','social_security', 'job_title', 'weekly_salary')   

class delete_EmployeeForm(forms.ModelForm):
 
    class Meta:
        model = Employee
        exclude = ['user']
        fields = ('name','social_security')     

class InvoiceForm(forms.ModelForm):
 
    class Meta:
        model = Invoice
        exclude = ['user']
        fields = ('name', 'invoice_type', 'invoice_reference', 'invoice_type', 'payment_frequency', 'amount')

class delete_InvoiceForm(forms.ModelForm):
 
    class Meta:
        model = Invoice
        exclude = ['user']
        fields = ('name','invoice_reference')   

class CreditForm(forms.ModelForm):
 
    class Meta:
        model = Credit
        exclude = ['user']
        fields = ('name', 'payment_reference', 'amount', 'payment_type', 'country', 'payment_location')

class delete_CreditForm(forms.ModelForm):
 
    class Meta:
        model = Credit
        exclude = ['user']
        fields = ('name','payment_reference')  

class AnalyticsForm(forms.ModelForm):
 
    class Meta:
        model = Analytics
        exclude = ['user']
        fields = ('clicks', 'impressions','conversions', 'sales', 'site')       

templates/base/basejs.html
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.0.0-alpha1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/crossfilter/1.3.12/crossfilter.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dc/2.1.9/dc.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/keen-js/4.3.0/keen.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js"></script>

templates/base/stripe.html
<script>
$(function() {
    $("#register-form").submit(function() {
        var form = this;   
        var card = {
          number:   $("#id_credit_card_number").val(),
          expMonth: $("#id_expiry_month").val(),
          expYear:  $("#id_expiry_year").val(),
          cvc:      $("#id_cvv").val()
        };
   
        $("#validate_card_btn").attr("disabled", true);
         Stripe.createToken(card, function(status, response) {
          if (status === 200) {
            console.log(status, response);
            $("#credit-card-errors").hide();
            $("#id_stripe_id").val(response.id);
            form.submit();
   
          } else {
            $("#stripe-error-message").text(response.error.message);
            $("#credit-card-errors").show();
            $("#validate_card_btn").attr("disabled", false);
          }
        });
        return false;    
    });
  });
</script>